### PR TITLE
Fixed inconsistencies and bugs in types + added missing fields

### PR DESCRIPTION
**Pull request by pilwon**
This PR fixes various inconsistencies in types.
It also adds missing fields summarized in #23.

### CODE REVIEW

**Comment by fermayo** [comment]
@MaximeHeckel can you check this?

**Comment by MaximeHeckel** [comment]
Hey @pilwon sorry for the delay, I'll check your changes

**Comment by MaximeHeckel** [comment]
It's merged on staging see 59bd3bf9f237f72bd860f5fb6066f7b277ccbfbd

**Comment by pilwon** [comment]
@MaximeHeckel :+1:

**Pull request closed without merging**
